# Generated by Django 5.2.1 on 2025-05-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('RUB', '₽'), ('UZS', "so'm")], default=('USD', '$'), max_length=10),
        ),
    ]
