# Generated by Django 5.2.1 on 2025-05-30 09:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('Agentagent', 'Agent'), ('Testimonialtestimonial', 'Testimonial')], default='Agentagent', max_length=50)),
                ('full_name', models.CharField(max_length=225)),
                ('image', models.ImageField(blank=True, null=True, upload_to='agent_images')),
                ('job', models.CharField(max_length=225)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
    ]
