# Generated by Django 5.2.1 on 2025-05-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='agent',
            name='full_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='agent_images'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='full_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial_images'),
        ),
    ]
