# Generated by Django 5.2.1 on 2025-05-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_agent_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('testimonial', 'Testimonial')], default='agent', max_length=50),
        ),
    ]
