# Generated by Django 5.2.1 on 2025-05-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sub Email',
                'verbose_name_plural': 'Sub Emails',
            },
        ),
    ]
