# Generated by Django 5.2.1 on 2025-05-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subemail',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='subemail',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subemail',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
